version: '3.1'

services:
  web:
    build:
      context: ./nginx
    image: nginx:alpine
    container_name: web
    tty: true
    ports:
      - "80:80"
    restart: always
    networks:
      - fullcycledesafio
    depends_on:
      - app
  app:
    build: 
      context: node
      dockerfile: Dockerfile
    image: node:15
    container_name: app
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - "8080:8080"
    networks:
      - fullcycledesafio
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_USER: nodedb
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - fullcycledesafio
networks:
  fullcycledesafio:
    driver: bridge