version: '3'

services:
  web:
    build:
      context: ./nginx
    image: marcelolourenco/nginx
    container_name: web
    tty: true
    ports:
      - "8080:80"
    restart: always
    networks:
      - fullcycledesafio
    depends_on:
      - app
  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: marcelolourenco/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    container_name: app
    tty: true
    volumes:
      - ./node:/usr/src/app
    networks:
      - fullcycledesafio
    working_dir: /usr/src/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
      MYSQL_USER: nodedb
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - fullcycledesafio
networks:
  fullcycledesafio:
    driver: bridge